name: Run Spring Boot Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Or 'zulu', 'microsoft', etc.
          java-version: '21'

      - name: Ensure mvnw is executable
        run: chmod +x mvnw

      - name: Build and test
        run: ./mvnw clean verify

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports